update datamountspawner behaviour

diff --git a/outposts/kube/values/base/config.yaml b/outposts/kube/values/base/config.yaml
--- a/outposts/kube/values/base/config.yaml
+++ b/outposts/kube/values/base/config.yaml
@@ -1,5 +1,5 @@
 extraPythonPackages:
-  - jupyterhub-datamountspawner==1.0.7
+  - jupyterhub-datamountspawner==1.1.1
   - jupyterhub-kubespawner==7.0.0
 extraVolumes:
   - configMap:
@@ -16,6 +16,7 @@ extraVolumeMounts:
   - mountPath: /etc/localtime
     name: tz-config
 outpostConfig: |
+  import base64
   import json
   import logging
   import os
@@ -112,7 +113,6 @@ outpostConfig: |
       privaterepopassword = spawner.user_options.get("custom", {}).get("privaterepopassword", False)
       if privaterepo and privaterepousername and privaterepopassword:
           try:
-              import base64
               auth_string = f"{privaterepousername}:{privaterepopassword}"
               auth_encoded = base64.b64encode(auth_string.encode()).decode()
               dockerregistry_plain_dict = {
@@ -475,10 +475,12 @@ outpostConfig: |
       return init_mounts
 
   def get_data_mount_config(spawner, user_options):
+      if user_options["option"] not in lmod_options:
+          return 'c.DataMount.templates = ["b2drop","aws","s3","webdav","generic"]'
       unity_userinfo_url = "https://login.jsc.fz-juelich.de/oauth2/userinfo"
       data_mount_config = """
-  # c.ServerApp.default_url="/lab/tree/home/jovyan"
-
+  c.NotebookApp.root_dir = "/"
+  c.LabApp.default_url = "/lab/tree/home/jovyan"
   def get_access_token():
       import os
       import requests
@@ -549,7 +551,7 @@ outpostConfig: |
                   continue
               if account == preferred_username and project not in projects:
                   projects.append(project)
-      
+
       project_dirs = [{"value": "/p/project1/{x}".format(x=x), "label": "$PROJECT {x}".format(x=x), "options": {"group": x}} for x in projects]
       scratch_dirs = [{"value": "/p/scratch/{x}".format(x=x), "label": "$SCRATCH {x}".format(x=x), "options": {"group": x}} for x in projects]
       ret = [{"value": "/p/home/jusers/{preferred_username}".format(preferred_username=preferred_username), "label": "$HOME", "options": {}}]
@@ -562,10 +564,108 @@ outpostConfig: |
 
   c.DataMount.uftp_auth_values = [{"label": "JUDAC", "value": "https://uftp.fz-juelich.de/UFTP_Auth/rest/auth/JUDAC"}]
   c.DataMount.uftp_label = "JUST"
-      """.replace("{unity_userinfo_url}", unity_userinfo_url)
+  """.replace("{unity_userinfo_url}", unity_userinfo_url)
       
       return data_mount_config
 
+
+  def custom_image_start_script(spawner):
+      datamount_version = f"=={spawner.data_mount_extension_version}" if spawner.data_mount_extension_version else ""
+
+      # export JUPYTER_CONFIG_PATH="..JUPYTER_CONFIG_PATH....JUPYTER_CONFIG_PATH:.../mnt/datamount_start" in b64, so helm can handle it
+      jupyter_config_path_b64 = base64.b64decode("ZXhwb3J0IEpVUFlURVJfQ09ORklHX1BBVEg9IiR7SlVQWVRFUl9DT05GSUdfUEFUSDorJEpVUFlURVJfQ09ORklHX1BBVEg6fS9tbnQvZGF0YW1vdW50X3N0YXJ0Igo=").decode()
+      jupyter_config_dir_b64 = base64.b64decode("ZXhwb3J0IEpVUFlURVJfQ09ORklHX0RJUj0iJHtKVVBZVEVSX0NPTkZJR19ESVI6KyRKVVBZVEVSX0NPTkZJR19ESVI6fS9tbnQvZGF0YW1vdW50X3N0YXJ0Igo=").decode()
+      return """#!/bin/sh
+
+  # 1. Check if user is root
+  if [ "$(id -u)" -eq 0 ]; then
+      echo "[INFO] Running as root."
+
+      # 2. Check if pip exists, if not: install Python + pip
+      if ! command -v pip >/dev/null 2>&1; then
+          echo "[INFO] pip not found. Installing Python and pip..."
+
+          if command -v apk >/dev/null 2>&1; then
+              apk add --no-cache python3 py3-pip shadow gcc python3-dev musl-dev linux-headers bash
+          elif command -v apt-get >/dev/null 2>&1; then
+              apt-get update && apt-get install -y python3 python3-pip adduser python3-venv bash passwd
+          elif command -v dnf >/dev/null 2>&1; then
+              dnf install -y python3 python3-pip shadow-utils util-linux bash
+          else
+              echo "[ERROR] Unsupported package manager. Install Python manually."
+              exit 1
+          fi
+      fi
+
+      env | grep -vE '^(PWD|HOME|SHLVL|OLDPWD|_)=|SCOPE' > /tmp/jovyan.env
+      printf "$JUPYTERHUB_OAUTH_SCOPES" > /tmp/jovyan_JUPYTERHUB_OAUTH_SCOPES.env
+      printf "$JUPYTERHUB_OAUTH_ACCESS_SCOPES" > /tmp/jovyan_JUPYTERHUB_OAUTH_ACCESS_SCOPES.env
+      printf "$JUPYTERHUB_OAUTH_CLIENT_ALLOWED_SCOPES" > /tmp/jovyan_JUPYTERHUB_OAUTH_CLIENT_ALLOWED_SCOPES.env
+      SCRIPT="$(realpath "$0")"
+      
+      # 4. Create jovyan user if missing
+      if ! id jovyan >/dev/null 2>&1; then
+          echo "[INFO] Creating user jovyan..."
+          useradd -m jovyan 2>/dev/null || adduser -D jovyan
+          if [ -d /etc/skel ]; then
+              cp -a /etc/skel/. /home/jovyan/
+          fi
+          chown -R jovyan:jovyan /home/jovyan
+          python3 -m venv /tmp/jupyterhub_venv
+          
+          chown -R jovyan:jovyan /tmp/jupyterhub_venv
+      fi
+      exec su - jovyan -c "$SCRIPT"
+      
+  fi
+
+  echo "[INFO] Running as user $(whoami)"
+
+  if [ -f /tmp/jovyan.env ]; then
+      set -a
+      . /tmp/jovyan.env
+      set +a
+      export JUPYTERHUB_OAUTH_SCOPES=$(cat /tmp/jovyan_JUPYTERHUB_OAUTH_SCOPES.env)
+      export JUPYTERHUB_OAUTH_ACCESS_SCOPES=$(cat /tmp/jovyan_JUPYTERHUB_OAUTH_ACCESS_SCOPES.env)
+      export JUPYTERHUB_OAUTH_CLIENT_ALLOWED_SCOPES=$(cat /tmp/jovyan_JUPYTERHUB_OAUTH_CLIENT_ALLOWED_SCOPES.env)
+  fi
+
+  if [ -f /tmp/jupyterhub_venv/bin/activate ]; then
+      . /tmp/jupyterhub_venv/bin/activate
+  fi
+
+  # 7. Ensure jupyterhub-singleuser in desired version range
+  if command -v pip >/dev/null 2>&1; then
+      if ! command -v jupyterhub-singleuser >/dev/null 2>&1; then
+          echo "[INFO] Installing jupyterhub-singleuser (current: $version)"
+          if [ -n "$VIRTUAL_ENV" ]; then
+              pip install jupyterhub jupyterlab
+          else
+              pip install --user jupyterhub jupyterlab
+          fi
+      fi
+
+      # 8. Install jupyterlab-data-mount
+      echo "[INFO] Installing jupyterlab-data-mount..."
+      if [ -n "$VIRTUAL_ENV" ]; then
+          pip install jupyterlab-data-mount{datamount_version}
+      else
+          pip install --user jupyterlab-data-mount{datamount_version}
+      fi
+  fi
+
+  # 9. Set config path
+  {jupyter_config_path_b64}
+  {jupyter_config_dir_b64}
+
+  # 10. Launch
+  echo $JUPYTER_CONFIG_PATH
+  if command -v start-singleuser.sh >/dev/null 2>&1; then
+      exec start-singleuser.sh
+  else
+      exec jupyterhub-singleuser
+  fi
+  """.replace("{datamount_version}", datamount_version).replace("{jupyter_config_path_b64}", jupyter_config_path_b64).replace("{jupyter_config_dir_b64}", jupyter_config_dir_b64)
 
   async def profile_list(spawner):
       # We're loading this config file for each Spawner object
@@ -602,58 +702,9 @@ outpostConfig: |
       }
 
 
-      if spawner.user_options["service"] == "jupyterlab" and (spawner.user_options["option"] in ["repo2docker", "custom"] or spawner.user_options["option"] in lmod_options):
-          version = f"=={spawner.data_mount_extension_version}" if spawner.data_mount_extension_version else ""
-          write_config_cmd = ""
-          if data_mount_config:
-              import base64
-              datamount_start_singleuser_sh = "IyEvYmluL3NoCiMgRXhwb3J0IGNvbmZpZyBwYXRoCmV4cG9ydCBKVVBZVEVSX0NPTkZJR19QQVRIPSIke0pVUFlURVJfQ09ORklHX1BBVEg6KyRKVVBZVEVSX0NPTkZJR19QQVRIOn0vdG1wL2RhdGFfbW91bnRfY29uZmlnIgoKIyBEZWZhdWx0IHN0YXJ0dXAgbG9naWMKY29tbWFuZCAtdiBzdGFydC1zaW5nbGV1c2VyLnNoID4vZGV2L251bGwgMj4mMSAmJiBleGVjIHN0YXJ0LXNpbmdsZXVzZXIuc2ggfHwgZXhlYyBqdXB5dGVyaHViLXNpbmdsZXVzZXIK"
-              data_mount_config_b64 = base64.b64encode(
-                  data_mount_config.encode()
-              ).decode()
-              write_config_cmd = f"""
-              mkdir -p /tmp/data_mount_config && \
-              echo '{data_mount_config_b64}' | base64 -d > /tmp/data_mount_config/jupyter_notebook_config.py && \
-              echo '{datamount_start_singleuser_sh}' | base64 -d > /tmp/data_mount_config/datamount_start-singleuser.sh && \
-              chmod +x /tmp/data_mount_config/datamount_start-singleuser.sh && \
-              """
-          install_cmd = ""
-          if spawner.user_options["option"] in ["repo2docker", "custom"]:
-              install_cmd = """
-              # Get the current jupyterhub-singleuser version
-              version=$(jupyterhub-singleuser --version || echo "0.0.0")
-              
-              # Set the desired version range
-              min_version="4.0.0"
-              max_version="5.0.0"
-              target_version="4.1.6"
-              
-              # Function to check if the version is in range
-              in_range() {
-                  [ "$(printf '%s\n' "$min_version" "$1" | sort -V | head -n1)" = "$min_version" ] && \
-                  [ "$(printf '%s\n' "$1" "$max_version" | sort -V | head -n1)" = "$1" ]
-              }
-              
-              # Check if the current version is within the range
-              if ! in_range "$version"; then
-                  echo "Installing jupyterhub-singleuser $target_version as version $version is not within $min_version - $max_version."
-                  pip install "jupyterhub==$target_version"
-              else
-                  echo "jupyterhub-singleuser $version is within the required version range."
-              fi
-              
-              # Install jupyterlab-data-mount extension with optional version
-              pip install --user jupyterlab-data-mount{version} && \\
-              """.replace("{version}", version)
-          cmd = [
-              '''
-              {install_cmd}
-              {write_config_cmd}
-              [ -x /tmp/data_mount_config/datamount_start-singleuser.sh ] && exec /tmp/data_mount_config/datamount_start-singleuser.sh || (command -v start-singleuser.sh >/dev/null 2>&1 && exec start-singleuser.sh || exec jupyterhub-singleuser)
-              '''.replace("{write_config_cmd}", write_config_cmd).replace("{install_cmd}", install_cmd)
-          ]
+      if spawner.user_options["service"] == "jupyterlab" and spawner.user_options["option"] == "custom":
+          kubespawner_override["data_mount_start"] = custom_image_start_script
 
-      kubespawner_override["cmd"] = cmd
       
       storage = await get_storage(spawner)
       if storage:
