prepare maintenance , set replicas to 0 on new prod cluster

diff --git a/outposts/unicore/kustomize-maint/jobs-3.3.yaml b/outposts/unicore/kustomize-maint/jobs-3.3.yaml
--- a/outposts/unicore/kustomize-maint/jobs-3.3.yaml
+++ b/outposts/unicore/kustomize-maint/jobs-3.3.yaml
@@ -1,7 +1,7 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: unicore-jobs-4-2-juniq
+  name: unicore-jobs-3-3
   namespace: unicore
 data:
   input_start.sh: |
@@ -57,8 +57,6 @@ data:
       export HOSTNAME_S=$(hostname -s)
       if [[ ${SYSTEMNAME} == "deep" ]]; then
         export HOSTNAME_I=${HOSTNAME_S}
-      elif [[ ${SYSTEMNAME} == "jedi" ]]; then
-        export HOSTNAME_I=$(hostname -s)-interconnect-1
       else
         export HOSTNAME_I=$(hostname -s)i
       fi
@@ -107,7 +105,7 @@ data:
         do
           HTTPCODE=$(curl -X "GET" ${CURL_ARGS} ${HUB_PROTO}://${ALL_REMOTE_NODES[$index]}:${REMOTE_PORT}/hub/api)
           if [[ ${HTTPCODE} -ge 200 ]] && [[ ${HTTPCODE} -le 299 ]]; then
-            if [[ ${SYSTEMNAME} == "deep" || ${SYSTEMNAME} == "jedi" ]]; then
+            if [[ ${SYSTEMNAME} == "deep" ]]; then
               export JUPYTERHUB_API_URL="${HUB_PROTO}://${ALL_REMOTE_NODES[$index]}:${REMOTE_PORT}/hub/api"
               export SSH_NODE=${ALL_REMOTE_NODES[$index]}
               echo "$(date) - Use ${JUPYTERHUB_API_URL} to communicate with JupyterHub and ${SSH_NODE} as jump node."
@@ -244,133 +242,39 @@ data:
         source ${HOME}/.jupyter/start_jupyter-jsc.sh
         send_spawn_update_warning 80 "Load customized modules done" "You are using a customized modules script, defined in ${HOME}/.jupyter/start_jupyter-jsc.sh."
       else
-        send_spawn_update 70 "Load default modules ..." "Loading Jupyter-bundle/20240520 in Stages/2024."
-
+        send_spawn_update 70 "Load default modules ..." "Loading JupyterCollection/2022.3.3 in Stages/2022."
         module purge
         module use ${OTHERSTAGES}
-        module load Stages/2024 GCC/12.3.0 ParaStationMPI
-        module load Jupyter-bundle/20240520
-        module load Cartopy/0.22.0 Cirq/1.4.0 DWave/6.8.0 PyQuil/4.8.0 CUDA/12 cuQuantum-Python/23.10.0-CUDA-12 Qiskit/0.45.1 pulser/0.18.0 qoqo-quest/0.14.4a3-CUDA-12-Rust-1.70.0 myqlm/1.10.4 ParityOS/2.3.0
+        module load Stages/2022 
+        module load GCCcore/.11.2.0 Python JupyterCollection/2022.3.3
 
-        # Kernels
-        if [[ $JUPYTER_MODULE_BASH_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-Bash/.0.9.3-4.2.1
-        fi
-        if [[ $JUPYTER_MODULE_CLING_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-Cling/.20231018-4.2.1
-        fi
-        if [[ $JUPYTER_MODULE_JAVA_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-Java/.1.3.0
-        fi
-        if [[ $JUPYTER_MODULE_JULIA_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-Julia/.1.9.3
-        fi
-        if [[ $JUPYTER_MODULE_LFORTRAN_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-LFortran/.0.30.0
-        fi
-        if [[ $JUPYTER_MODULE_OCTAVE_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-Octave/.8.4.0-4.2.1
-        fi
-        if [[ $JUPYTER_MODULE_R_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-R/.4.3.2-4.2.1
-        fi
-        if [[ $JUPYTER_MODULE_RUBY_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-Ruby/.3.2.2
-        fi
-        if [[ $JUPYTER_MODULE_PYDEEPLEARNING_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-PyDeepLearning/.2024.3-4.2.1
-        fi
-        if [[ $JUPYTER_MODULE_PYEARTHSYSTEM_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-PyEarthSystem/.2024.3-4.2.1
-        fi
-        if [[ $JUPYTER_MODULE_PYQUANTUM_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-PyQuantum/.2024.10-4.2.1
-        fi
-        if [[ $JUPYTER_MODULE_PYVISUALIZATION_ENABLED -eq 1 ]]; then
-          module load JupyterKernel-PyVisualization/.2024.3-4.2.1
-        fi
-
-        # Proxies
-        if [[ $JUPYTER_MODULE_XPRAHTML5_ENABLED -eq 1 ]]; then
-          module load JupyterProxy-XpraHTML5/.0.4.0-4.2.1
-        fi
-         # Load MatLab Proxy module, if user is in matlab group
-        IFS=' ' read -ra groups_array <<< "$(id -Gn)"
-        for group in "${groups_array[@]}"; do
-          if [[ "$group" == "matlab" ]]; then
-            module load JupyterProxy-Matlab/.0.12.2-4.2.1
-            break
-          fi
-        done
-        # NEST does not support nodejs v 18 ( https://github.com/nest-desktop/nest-desktop/issues/509 )
-        if [[ $JUPYTER_MODULE_NEST_ENABLED -eq 1 ]]; then
-          if [[ $SYSTEMNAME != "hdfml" ]]; then
-            module load JupyterProxy-NESTDesktop/.0.4.0-4.2.1
-          fi
-        fi
-
-        if [[ $JUPYTER_MODULE_RSTUDIO_ENABLED -eq 1 ]]; then
-          if [[ $SYSTEMNAME != "deep" ]]; then
-            module load JupyterProxy-RStudio/.2023.09.1-4.2.1
-          fi
-        fi
-        # Extensions
-        if [[ $JUPYTER_MODULE_NGLVIEW_ENABLED -eq 1 ]]; then
-          module load nglview/.3.1.2
-        fi
-        if [[ $JUPYTER_MODULE_JUPYTERAI_ENABLED -eq 1 ]]; then
-          module load jupyter-ai/.2.15.0
-        fi
-        if [[ $JUPYTER_MODULE_VARIABLEINSPECTOR_ENABLED -eq 1 ]]; then
-          module load jupyterlab-variableinspector/.3.2.1
-        fi
-        if [[ $JUPYTER_MODULE_SPELLCHECKER_ENABLED -eq 1 ]]; then
-          module load jupyterlab-spellchecker/.0.8.4
-        fi
-        if [[ $JUPYTER_MODULE_TRAMEMANAGER_ENABLED -eq 1 ]]; then
-          if [[ $SYSTEMNAME != "deep" ]]; then
-            module load jupyterlab-trame-manager/.0.6.1-4.2.1
-          fi
-        fi
-        if [[ $JUPYTER_MODULE_SLURMWRAPPER_ENABLED -eq 1 ]]; then
-          module load jupyter-slurm-provisioner/.0.6.0-4.2.1
-          export SLURMEL_DOCUMENTATION_HREF="https://docs.jupyter.jsc.fz-juelich.de/github/FZJ-JSC/jupyter-jsc-notebooks/blob/documentation/05-News&Updates/Announcement-2022-12_Slurm_Wrapped_Kernels.ipynb"
-          export JUPYTERJSC_CMD_ARGS="${JUPYTERJSC_CMD_ARGS} --ServerApp.kernel_manager_class=jupyter_slurm_provisioner.SlurmAsyncMappingKernelManager"
-          export SLURM_PROVISIONER_NODE_SUFFIX="i"
-          export SLURM_PROVISIONER_JHUB_METRICS="${JUPYTERHUB_API_URL}/slurmwrapper/${JUPYTERHUB_USER}/${JUPYTERHUB_SERVER_NAME}"
-          test -d ${HOME}/.local/share/jupyter/kernels.deactivated/slurm-provisioner-kernel && ! test -d ${HOME}/.local/share/jupyter/kernels/slurm-provisioner-kernel && mv ${HOME}/.local/share/jupyter/kernels.deactivated/slurm-provisioner-kernel ${HOME}/.local/share/jupyter/kernels/slurm-provisioner-kernel
-        else
-          test -d ${HOME}/.local/share/jupyter/kernels/slurm-provisioner-kernel && mkdir -p ${HOME}/.local/share/jupyter/kernels.deactivated && mv ${HOME}/.local/share/jupyter/kernels/slurm-provisioner-kernel ${HOME}/.local/share/jupyter/kernels.deactivated/slurm-provisioner-kernel
-        fi
+        echo "$(date) - checking for GPU"
         lspci -k | grep -A 2 -i "NVIDIA" | grep "Kernel driver in use:" | grep "nvidia"
         if [ $? -eq 0 ]; then
-          module load jupyterlab-nvdashboard/.0.10.0
+          send_spawn_update 75 "Load Nvidia module ..." "Loading JupyterExtension-nvdashboard/0.6.0-2022.3.3 in Stages/2022."
+          module load JupyterExtension-nvdashboard/0.6.0-2022.3.3
         fi
-        send_spawn_update 80 "Load default modules done" "Loaded Jupyter-bundle/20240300 in Stages/2024."
+        send_spawn_update 80 "Load default modules done" "Loading JupyterCollection/2022.3.3 in Stages/2022."
       fi
       echo "$(date) - Load modules done"
     }
 
     update_config () {
       sed -i -e "s|_port_|${PORT}|g" -e "s|_home_|${JUPYTERHUB_HOME:-${HOME}}|g" -e "s|_servername_|${JUPYTERHUB_SERVER_NAME}|g" ${DIR}/config.py
-      send_spawn_update 85 "Add system specific configuration." "Use system specific jupyter_notebook_config.py files"
       if [[ -f ${EBROOTJUPYTERLAB}/etc/jupyter/jupyter_notebook_config.py ]]; then
+        echo "$(date) - Add system specific config ..."
+        send_spawn_update 85 "Add system specific configuration." "Use system specific config file ${EBROOTJUPYTERLAB}/etc/jupyter/jupyter_notebook_config.py"
         echo "" >> ${DIR}/config.py
         cat ${EBROOTJUPYTERLAB}/etc/jupyter/jupyter_notebook_config.py >> ${DIR}/config.py
-        echo "$(date) - Added system specific config ${EBROOTJUPYTERLAB}/etc/jupyter/jupyter_notebook_config.py"
+        for path in ${JUPYTER_EXTRA_LABEXTENSIONS_PATH//:/$'\n'}; do
+          echo "c.LabServerApp.extra_labextensions_path.append('$path')" >> ${JUPYTER_LOG_DIR}/config.py
+        done
+        echo "$(date) - Add system specific config done"
       fi
-      if [[ -f ${EBROOTJUPYTERMINRESOURCEMINUSAGE}/etc/jupyter/jupyter_notebook_config.py ]]; then
-        echo "" >> ${DIR}/config.py
-        cat ${EBROOTJUPYTERMINRESOURCEMINUSAGE}/etc/jupyter/jupyter_notebook_config.py >> ${DIR}/config.py
-        echo "$(date) - Added system specific config ${EBROOTJUPYTERMINRESOURCEMINUSAGE}/etc/jupyter/jupyter_notebook_config.py"
-      fi
-      for path in ${JUPYTER_EXTRA_LABEXTENSIONS_PATH//:/$'\n'}; do
-        echo "c.LabServerApp.extra_labextensions_path.append('$path')" >> ${JUPYTER_LOG_DIR}/config.py
-      done
-      if command -v update_favorites_json &> /dev/null; then
+      if [[ -f ${EBROOTJUPYTERLAB}/bin/update_favorites_json ]]; then
         # update favorite-dirs with $HOME,$PROJECT,$SCRATCH,
         echo "$(date) - Update favorites"
-        update_favorites_json
+        ${EBROOTJUPYTERLAB}/bin/update_favorites_json
       fi
     }
 
@@ -493,3 +397,105 @@ data:
     load_project_specific_kernel
     start
 
+    #!/bin/bash
+
+    # Catch SIGTERM signal and stop $child process
+    _term() {
+      echo "$(date) - Stop JupyterLab ..."
+      if [[ -z $child ]]; then
+        echo "$(date) - Stop JupyterLab - unknown PID. Start stop.sh to wait for PID"
+        bash ${DIR}/stop.sh &
+      else
+        pkill --parent $child
+        kill $child
+        echo "$(date) - Stop JupyterLab ( $child ) ... done"
+        if [[ -z $token_pid ]]; then
+          echo "$(date) - Validate Token PID not found..."
+        else
+          echo "$(date) - Stop Validate Token Script ( $token_pid ) ..."
+          kill $token_pid
+          echo "$(date) - Stop Validate Token Script ( $token_pid ) ... done"
+        fi
+      fi
+    }
+    trap _term SIGTERM
+
+    # System specific requirements
+    requirements () {
+      echo "$(date) - Setup system specific requirements ( ${HOSTNAME} ) ..."
+      if [[ ! -d ${HOME}/.cache/black/19.3b0 ]]; then
+        mkdir -p ${HOME}/.cache/black/19.3b0
+      fi
+      # export a memory warn threshold on login nodes
+      hostname | egrep '<hostname_base>' > /dev/null && export JUPYTER_MEMWARNTHRES=0.5
+      # set cpu limit/warning
+      export FPATH_CPUQUOTA="/sys/fs/cgroup/cpu,cpuacct/user.slice/user-$(id -u $USER).slice/cpu.cfs_quota_us"
+      [ -f "${FPATH_CPUQUOTA}" ] && [ $(hostname | egrep '<hostname_cpulimit>') ] && export JUPYTER_CPULIMIT=$(($(cat ${FPATH_CPUQUOTA})/100000))
+      
+      echo "$(date) - Setup system specific requirements done"
+    }
+
+    # set env_variables correctly
+    set_env () {
+      echo "$(date) - Set environment variables ..."
+      export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+      export PID_PATH=${DIR}/service.pid
+      export VALIDATE_TOKEN_PID_PATH=${DIR}/validate_token.pid
+      export LC_ALL=en_US.UTF-8
+      export JUPYTER_LOG_DIR=${DIR}
+      export JUPYTER_STDOUT=${JUPYTER_LOG_DIR}/stderr
+      export PYTHONPATH=""
+      export PYTHONNOUSERSITE=1
+      HOSTNAME_S=$(hostname -s)
+      # If this JupyterLab is running on a LoginNode, we'll use the external api url. Otherwise we have to use a LoginNode as Proxy.
+      if [[ ${HOSTNAME_S} == "<hostname_base>"* ]]; then
+        unset JUPYTERHUB_SSL_CLIENT_CA
+        export JUPYTERHUB_API_URL=<jupyterhub_api_url>
+        export JUMP_NODE=${HOSTNAME_S}
+        echo "$(date) - Use ${JUPYTERHUB_API_URL} to communicate with JupyterHub. Jump node for tunnel: ${JUMP_NODE}"
+        export CURL_ARGS="--silent --write-out %{http_code} --output /dev/null"
+      else
+        export REMOTE_PORT="<remote_port>"
+        export JUPYTERHUB_CERTIFICATE="${DIR}/notebooks-ca_trust.crt"
+        export CURL_ARGS="--silent --write-out %{http_code} --cacert ${JUPYTERHUB_CERTIFICATE} --output /dev/null"
+        # Look for random LoginNode
+        # We start at a random index, then we will run through all nodes and test them
+        export ALL_REMOTE_NODES=(<hostname_all>)
+        size=${#ALL_REMOTE_NODES[@]}
+        index=$(($RANDOM % $size))
+        start_index=$index
+        for _ in ${ALL_REMOTE_NODES[@]}
+        do
+          HTTPCODE=$(curl -X "GET" ${CURL_ARGS} https://${ALL_REMOTE_NODES[$index]}:${REMOTE_PORT}/hub/api)
+          if [[ ${HTTPCODE} -ge 200 || ${HTTPCODE} -lt 299 ]] ; then
+            export JUPYTERHUB_API_URL="https://${ALL_REMOTE_NODES[$index]}:${REMOTE_PORT}/hub/api"
+            export JUMP_NODE=${ALL_REMOTE_NODES[$index]}
+            echo "$(date) - Use ${JUPYTERHUB_API_URL} to communicate with JupyterHub and ${JUMP_NODE} as jump node."
+            break
+          fi
+          index=$(expr $index + 1)
+          if [[ $index == $size ]]; then
+            index=0
+          fi
+          if [[ $index == $start_index ]]; then
+            echo "$(date) - Could not find any LoginNode to connect to JupyterHub. Please try again in a few minutes."
+            exit 1
+          fi
+        done
+        export JUPYTERHUB_SSL_CLIENT_CA="${DIR}/service_ca.crt"
+      fi
+      export JUPYTERHUB_ACTIVITY_URL=${JUPYTERHUB_API_URL}/users/${JUPYTERHUB_USER}/activity
+      export JUPYTERHUB_API_TOKEN=$(cat ${DIR}/.jupyter.token)
+      export JUPYTERHUB_OAUTH_SCOPES=$(cat ${DIR}/.oauth.scopes)
+      export JUPYTERHUB_SINGLEUSER_APP="jupyter_server.serverapp.ServerApp"
+      export JUPYTERHUB_SSL_KEYFILE="${DIR}/service_cert.key"
+      export JUPYTERHUB_SSL_CERTFILE="${DIR}/service_cert.crt"
+      export JUPYTERJSC_CMD_ARGS=""
+      export PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
+      echo "$(date) - Set environment variables done"
+    }
+
+    requirements
+    set_env
+    send_spawn_update_fail "JupyterLab 3.3 no longer supported on ${SYSTEMNAME}. Please update to version 3.6" "Update this JupyterLab configuration or delete this one and create a new one with 3.6."
+    exit 1
